### ISSUE TITLE
Allow bypassing the confirmation prompt?

### ISSUE THREAD

**Issue by cowboy** [codemodsquad/astx#8]
I'm about to update a hundred files in a large repo, is there any way to bypass the confirmation prompt (via a `-y` flag or similar) so that it just applies the changes to all files, that I can then review later, en masse?

**Comment by jedwards1211** [comment]
not yet, I'll add one.  Are you using a beta version?

**Comment by cowboy** [comment]
Yeah, I'm using the latest beta!
